Task1
Tenelles/TestGuru pull request #1
Opened 2020-12-21 13:43 UTC by Tenelles

Я случайно добавил в коммит разом все файлы, поэтому не получилось каждое изменение по заданию расписать :C

2020-12-21 15:33 UTC, VidgarVii requested changes

2020-12-21 15:33 UTC, VidgarVii commented on README.md
> +  * Преподаватель
очень много лишнего. Всякие вариантЫ, спискИ тут точно лишние. 
Сущности могут быть. Категория, Тест, Вопрос и т.д.

2020-12-21 15:33 UTC, VidgarVii commented on config/initializers/version.rb
> +Rails.configuration.version = File.read('config/version')
1. Версия указана не верно. У тебя еще приложения нет. А ты уже релиз объявил.
2. вообще не разобрал твою логику. Тут должен быть класс с 1 константой, в которой должна быть записана версия

2020-12-21 15:33 UTC, VidgarVii commented on public/about.html
> +    <p><i>This app was created for the ruby on Rails course by <a href="thinknetica.com">Thinknetica</a></i></p>
Принято, чтобы ссылки на внешние ресурсы открывались в новой вкладке. Мы же не хотим потерять пользователя.
А что бы не ругался робот, надо добавить атрибут rel="nofollow"

2020-12-21 16:07 UTC, Tenelles commented
Все никак не привыкну закрывать PR перед тем, как делать исправления. Уже наверное раз пятый коммиты сделаны в уже закрытом реквесте
Я исправлюсь, честно)

2020-12-21 18:12 UTC, VidgarVii requested changes

2020-12-21 18:12 UTC, VidgarVii commented on README.md
> +  > > > * Вариант ответа
чем отличается Вариант ответа и ответ?

2020-12-21 18:12 UTC, VidgarVii commented on README.md
> +  * Проверяющий
как это будет работать?) Какие данные содержать?

2020-12-21 18:12 UTC, VidgarVii commented on README.md
> +  * Студент
сойдет обычный пользователь) А мы точно про ПО говорим, в котором можно будет проходить тесты?

2020-12-21 19:01 UTC, Tenelles commented on README.md
> +  * Студент
Я тут пытался просто сделать пока наиболее приближенно к реальности писать, поэтому так и написал. Теперь понял, поправлю

2020-12-21 19:08 UTC, Tenelles commented on config/initializers/version.rb
> +config.version = '0.1.0'
Тут я почему-то решил, что просто определенный в этом месте класс не будет виден, но нужно было просто запустить консоль ¯\_(ツ)_/¯

2020-12-22 11:52 UTC, Tenelles commented
Попытался убрать лишние файлы

2020-12-22 16:21 UTC, VidgarVii requested changes

2020-12-22 16:21 UTC, VidgarVii commented on README.md
> +  * TestCategory
лучше будет просто Category. А для теста или нет определит связь.
так обеспечим более высокую связанность логики с объектом

2020-12-22 16:21 UTC, VidgarVii commented on README.md
> +  > * Answer
ответы скорей будут принадлежать вопросам, а не пользователям.
пользователи будут выбирать нужный ответ из списка
Еще надо где-то хранить результат прохождения теста

2020-12-22 16:21 UTC, VidgarVii commented on config/initializers/version.rb
> +  CURRENT_VERSION = '1.1.0'
CURRENT_VERSION не используется. 
просто VERSION

2020-12-22 16:21 UTC, VidgarVii commented on config/initializers/version.rb
> +  CURRENT_VERSION = '1.1.0'
к получению версии должен быть путь 
НазваниеПроекта::Application::VERSION

2020-12-22 16:21 UTC, VidgarVii commented on config/initializers/version.rb
> +  CURRENT_VERSION = '1.1.0'
константу надо фризить

2020-12-22 16:55 UTC, Tenelles commented
Исправлены замечания. Я не совсем понял, как создать класс, чтобы путь к версии бал TestGuru::Application::VERSION, поэтому просто назвал класс как TestGuru::Application. Надеюсь, правильно

2020-12-23 06:02 UTC, VidgarVii approved these changes

2020-12-23 17:17 UTC, merged